#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
fcitx5 &
picom & 
dunst &
feh --bg-center $HOME/Pictures/wall.jpg 
$HOME/.config/polybar/launch.sh
utools &
caffeine &
nm-applet &
pgrep -x mailspring > /dev/null || mailspring -b 
grep `pgrep Xorg` /tmp/init_redshift  > /dev/null || ~/.config/polybar/modules/redshift/redshift.sh on && echo `pgrep Xorg` > /tmp/init_redshift

if xrandr | grep "DisplayPort-1 connected" > /dev/null; then
    xrandr --output eDP --off --output DisplayPort-1 --primary --mode 3840x2160 --pos 0x0 --rotate normal
else
    xrandr --output eDP --primary --mode 2880x1800 --pos 0x0 --rotate normal --output DisplayPort-1 --off
fi

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a wechat.exe desktop=^3
bspc rule -a feishu desktop=^4
bspc rule -a Feishu desktop=^4
bspc rule -a Mailspring desktop=^5
bspc rule -a netease-cloud-music desktop=^6

# 修复不满屏
for side in top right bottom left; do bspc config ${side}_monocle_padding -10; done
